""" Necklace pipeline implemented in snakemake """

__author__ = "Sarah Hazell Pickering (sarah.pickering@anu.edu.au)"
__date__ = "2018-11-06"

include: "scripts/build_genome_guided_assembly.py"
include: "scripts/build_genome_superT.py"
include: "scripts/build_de_novo_assembly.py"
include: "scripts/build_relatedsp_superT.py"
include: "scripts/cluster.py"
include: "scripts/run_lace.py"
include: "scripts/map_reads_to_superT.py"
include: "scripts/get_counts.py"
include: "scripts/get_stats.py"

#configfile: "necklace.json"
DATASET = config["dataset"]
OUTPUT_DIR = "output_data/"

rule all:
    input: #files created by each step
        OUTPUT_DIR + "genome_guided_assembly/" + DATASET + "_assembly.gtf",
        OUTPUT_DIR + "genome_superT/" + DATASET + "_genome_superT.fa",
        OUTPUT_DIR + "de_novo_assembly/" + DATASET + "_de_novo.fa",
        #related species files are in a different folder and can be reused
        OUTPUT_DIR + "clustering/" + DATASET + ".clusters",
        OUTPUT_DIR + "superT/" + DATASET + "_SuperDuper.fa",
        expand (OUTPUT_DIR + "mapped_reads/{sample}.sum.txt", sample = config["samples"]),
        OUTPUT_DIR + "counts/" + DATASET + "_gene.counts",
        
        #final summary statistics
        OUTPUT_DIR + "stats/" + DATASET + ".sum.tab",
        OUTPUT_DIR + "stats/" + DATASET + "_rel_denovo.sum.tab",
        OUTPUT_DIR + "stats/" + DATASET + ".times.tab"
